### PR TITLE
Merge pull request #38 from AstarVienna/hb/movemicado

### PR DESCRIPTION
**Pull request by wjvriend**
Move micado directory so SourceDescriptionFitsKeywords works

### CODE REVIEW

**Comment by astronomyk** [comment]
@wjvriend is this PR still relevant?

**Comment by hugobuddel** [comment]
I recall that @wjvriend created this PR when there was some confusion about what version (that is, branch) of ScopeSIM_Templates should be used by MicadoWISE.

As can be seen in the network graph, everything in dev_micado has been merged into dev_master, and everything in dev_master is  merged into master. So it should be possible for MicadoWISE to use the master branch now: https://github.com/AstarVienna/ScopeSim_Templates/network

However, this PR is from dev_master into dev_micado. That essentially makes it the responsibility of @wjvriend, because @astronomyk should not have to worry about the dev_micado branch. The dev_micado branch was intended to be used by (the develop branch of) MicadoWISE if there are changes needed by MicadoWISE that have not yet been propagated to dev_master or master. (Or occasionally to deliberately not use new features in dev_master that are not compatible with MicadoWISE.) Merging dev_master into dev_micado does not need a merge request though, because it is not necessary to review the changes. I always did that on the command line directly.

It should not be necessary to use the dev_micado branch now. So I would propose to simply close this MR, and start using the master branch (or PyPI version once it is released) as a dependency of MicadoWISE (if possible). You can merge dev_master into dev_micado when we want to use dev_micado again for some reason. Maybe you could even remove the dev_micado branch for now for simplicity.

**Comment by wjvriend** [comment]
Thanks for explaining Hugo, I'm still a bit lost with all the branches here. Anyway I'll close this merge request.

**Comment by hugobuddel** [comment]
FWIW, I really like the network view in github, or graph view in gitlab (which is better) to get an overview of the branches. Or
```
git log --graph --all --oneline --decorate
```
like this:
Screenshot from 2022-10-13 11-24-10

**Pull request closed without merging**
