### PR TITLE
Add docstring tests to CI

### PR DESCRIPTION
**Pull request by hugobuddel**
See https://github.com/AstarVienna/DevOps/pull/36 and https://github.com/AstarVienna/ScopeSim_Templates/pull/105

### CODE REVIEW

**Review by teutoburg — COMMENTED** [review]
Why not just call the DevOps workflow? I thought that was the whole point of AstarVienna/DevOps#36?

Also, we could put this call in the existing tests.yml. Also, I don't think we need a `workflow_call` here.

**Comment by hugobuddel** [comment]
> Why not just call the DevOps workflow? I thought that was the whole point of [AstarVienna/DevOps#36](https://github.com/AstarVienna/DevOps/pull/36)?

Uh yes, this doesn't make sense. Not sure what I was thinking

**Comment by hugobuddel** [comment]
I don't really have time to do this properly now, and it is low priority, so I'm probably just going to leave this 'open' for long enough to move you from 'hey nice addition', to 'frustration that @hugobuddel leaves these PRs hanging so long', to indifference. Just a heads-up.

**Comment by teutoburg** [comment]
Mind if I hijack your branch and (attempt to) "do it properly" when I find time in the near future? 🙂

**Comment by hugobuddel** [comment]
> Mind if I hijack your branch and (attempt to) "do it properly" when I find time in the near future? 🙂

Yeah sure. Wanted to add that. Feel free to directly commit to it or rebase it or whatever :smiley_cat:

**Comment by teutoburg** [comment]
Since you gave me a free hand in rebasing this, I decided to just drop the commit that added the (imo) unnecessary workflow file, avoiding it being deleted in the (almost) very next commit. This also has the advantage that the file should not show up in the Actions tab of this repo, which seems to sometimes keep old workflow files, not sure why.

But now I finally got one of those "We went looking everywhere, but couldn’t find those commits.", so at least I now know what you mean with that 🙃

**Comment by teutoburg** [comment]
Now we get "ValueError: Quantity truthiness is ambiguous, especially for logarithmic units and temperatures. Use explicit comparisons." in the updated tests. I believe that has been fixed elsewhere?

**Comment by hugobuddel** [comment]
Thanks for fixing this.

Yeah that Quantity Truthiness is fixed in https://github.com/AstarVienna/speXtra/pull/57 but we have not released a new speXtra yet. It is kinda fine that things fail with the 'updated dependencies' test, as the goal of that is to learn about such problems early on. But on github we cannot mark tests as "please mark this specific test as failed but do not affect the combined test results". Oh well, incentivizes us to fix things. But it is unrelated to this PR.

Now it is unclear who should review and merge this. So I'm just going to merge it.

It would be 'interesting' to roll this out to the other repositories.

**Comment by hugobuddel** [comment]
Ugh... I can't think of any way to mark these as webtests too.. But hopefully they won't fail too often.

Or we install ScopeSim_Data before running these? Or do we do that anyway and are these files just missing.

For reference, this run failed: https://github.com/AstarVienna/ScopeSim_Templates/actions/runs/14678078259/job/41197230944

```
 _______________ [doctest] scopesim_templates.stellar.stars.stars _______________
180         >>> from scopesim_templates.stellar import stars
181         >>>
182         >>> n = 100
183         >>> spec_types = ["A0V", "G2V", "K0III", "M5III", "O8I"] * (n // 5)
184         >>> ids = np.random.randint(0, 5, size=n)
185         >>> star_list = [spec_types[i] for i in ids]
186         >>> mags = np.random.normal(loc=20, scale=3, size=n) * u.mag
187         >>> x, y = np.random.random(size=(2, n))
188         >>>
189         >>> src = stars("Ks", mags, spec_types, x, y)
UNEXPECTED EXCEPTION: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='svo2.cab.inta-csic.es', port=80): Max retries exceeded with url: /theory/fps3/fps.php?ID=2MASS/2MASS.Ks (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f12bf046330>, 'Connection to svo2.cab.inta-csic.es timed out. (connect timeout=30)'))"))
```

**Comment by teutoburg** [comment]
ScopeSim_Data _is_ installed during the doctests workflow. But [over there](https://github.com/AstarVienna/ScopeSim_Data/tree/main/scopesim_data), I only see skycalc-related files, no filter curves?

**Comment by hugobuddel** [comment]
> ScopeSim_Data _is_ installed during the doctests workflow. But [over there](https://github.com/AstarVienna/ScopeSim_Data/tree/main/scopesim_data), I only see skycalc-related files, no filter curves?

Oh, did I never get around to actually adding those? Or are they already/still in speXtra perhaps?

Yes they are in speXtra:

`Ks` should map to `2MASS/2MASS.Ks` according to https://github.com/AstarVienna/speXtra/blob/main/database/default_filters.yml , and that file is in the repository and should be installed with the package https://github.com/AstarVienna/speXtra/blob/main/spextra/data/svo/2MASS/2MASS.Ks and should therefore never be downloaded..

The goal was to move that data directory to ScopeSim_Data, but never got to that.

Oh well..

**Pull request merged**
